### ISSUE TITLE
Add to the Nix category on Hackage

### ISSUE THREAD

**Issue by expipiplus1** [ttuegel/autonix-deps-kf5#1]
https://hackage.haskell.org/packages/#cat:Nix

**Comment by ttuegel** [comment]
Done! Thanks for pointing this out.

**Comment by expipiplus1** [comment]
Cool, no problem!

**Comment by expipiplus1** [comment]
It's also possible to get Hackage to do this automatically by putting `Nix` in the category field of the `.cabal` file.

**Comment by ttuegel** [comment]
I edited the package description file of the most recently uploaded version on Hackage. I didn't update it on GitHub because the package is deprecated and I am not planning to make any more releases.
